#!/bin/bash
probe () {
  local name="$1" url="$2"
  local out
  out=$(curl -sS -o /dev/null -m 12 -w '%{http_code} %{size_download}' -L "$url" 2>&1 | tail -1)
  printf '%-34s %-16s %s\n' "$name" "$out" "$url"
}
probe "github-raw(control)"   "https://raw.githubusercontent.com/anthropics/anthropic-sdk-python/main/README.md"
probe "UK-HMLR-pricepaid"     "http://prod.publicdata.landregistry.gov.uk/pp-monthly-update-new-version.csv"
probe "UK-HMLR-sparql"        "https://landregistry.data.gov.uk/"
probe "IE-PPR"                "https://www.propertypriceregister.ie/"
probe "US-FHFA-hpi"           "https://www.fhfa.gov/hpi"
probe "US-Zillow-research"    "https://files.zillowstatic.com/research/public_csvs/zhvi/Metro_zhvi_uc_sfrcondo_tier_0.33_0.67_sm_sa_month.csv"
probe "US-FRED"               "https://fred.stlouisfed.org/graph/fredgraph.csv?id=CSUSHPINSA"
probe "US-census-bps"         "https://www.census.gov/construction/bps/"
probe "BIS-stats"             "https://data.bis.org/"
probe "DallasFed-intl-hp"     "https://www.dallasfed.org/research/international/houseprice"
probe "OECD-sdmx"             "https://sdmx.oecd.org/public/rest/dataflow/OECD.ECO.MPD"
probe "IMF-data"              "https://www.imf.org/en/Research/housing-market-stability"
probe "JP-MLIT-lib"           "https://www.reinfolib.mlit.go.jp/"
probe "KR-data.go.kr"         "https://www.data.go.kr/"
probe "SG-data.gov.sg"        "https://data.gov.sg/"
probe "SG-URA-api"            "https://www.ura.gov.sg/maps/api/"
probe "NL-kadaster"           "https://www.kadaster.nl/"
probe "PL-NBP-barn"           "https://nbp.pl/en/statistic-and-financial-reporting/real-estate-market/"
probe "IN-data.gov.in"        "https://www.data.gov.in/"
probe "IN-RBI-dbie"           "https://data.rbi.org.in/"
probe "IN-RBI-main"           "https://www.rbi.org.in/"
probe "IN-NHB-residex"        "https://residex.nhbonline.org.in/"
probe "IN-IGR-maharashtra"    "https://igrmaharashtra.gov.in/"
probe "IN-NGDRS"              "https://ngdrs.gov.in/"
probe "IN-DILRMP-dashboard"   "https://dilrmp.gov.in/"
probe "IN-MahaRERA"           "https://maharera.maharashtra.gov.in/"
probe "IN-bhuvan"             "https://bhuvan.nrsc.gov.in/"
probe "IN-mospi"              "https://www.mospi.gov.in/"
probe "JRC-GHSL"              "https://human-settlement.emergency.copernicus.eu/"
probe "OSM-overpass"          "https://overpass-api.de/api/status"
probe "OSM-geofabrik-india"   "https://download.geofabrik.de/asia/india.html"
probe "Google-open-buildings" "https://sites.research.google/gr/open-buildings/"
probe "WorldPop"              "https://hub.worldpop.org/"
probe "NOAA-VIIRS-eog"        "https://eogdata.mines.edu/products/vnl/"
probe "magicbricks-propindex" "https://www.magicbricks.com/"
probe "housing-datalabs"      "https://housing.com/news/data-labs/"
probe "knightfrank-in"        "https://www.knightfrank.co.in/research"
