#!/usr/bin/env python3
"""OP-D2 family F18 — KELLY/RUIN MATH on the F16/F17 P&L distributions (registered:
research/register/trial-ledger.md, Entry OP-D2, 2026-09-07): "F18 Kelly/ruin math on
F16/F17 P&L distributions: full-Kelly, half-Kelly, DD-constrained f
(P(book DD>10%)<=1%/yr) (3) — analytic on measured odds."

Registered cells (3) — family is ANALYTIC on measured odds; NO PASS/MISS bar was
registered, so every cell is DESCRIPTIVE:
  1. full_kelly       : f* = argmax_f E[ln(1 + f r)] on each measured distribution
  2. half_kelly       : f*/2 — growth given up + tail behaviour
  3. dd_constrained_f : max f with P(book maxDD > 10% within 1y) <= 1% (bootstrap on
                        the measured odds)

Declared conventions (header of record, fixed BEFORE the run):
  - Distributions REGENERATED by importing the parent scripts' own machinery
    (scripts/opt_sweep/f16.py, f17.py — parent designs quoted verbatim per process note
    #5; the F16 monthly walk below is f16.run()'s loop with ONLY a margin line added).
    No numbers copied from parent JSONs; vault data only, via the parents' loaders.
  - Unit of risk: per-cycle return ON MARGIN, margin = max wing width - credit (F17
    convention, applied identically to the F16 monthly condor at entry strikes/credit).
    f = fraction of book posted as margin per entered cycle; book *= (1 + f r) on
    entered cycles, flat otherwise.
  - Four measured arms: F16 monthly hold | F16 monthly stop-2x | F17 weekly hold |
    F17 weekly daily-stop.
  - full-Kelly: grid argmax of mean(log1p(f r)), f in (0, 0.999/|min r|) step 0.001
    (cap 10 if min r >= 0); f* = 0 if mean r <= 0. Growth/yr = exp(rate * E ln(1+f r))-1
    with rate = entries/span_years (measured, unrounded).
  - DD-constrained f: iid bootstrap of the measured cycle returns, numpy default_rng
    seed 42 PER ARM, 20000 one-year paths of n_cyc = max(1, round(rate)) cycles; wealth
    from W=1, maxDD vs running peak (peak floored at 1); largest f on a 0.005 grid,
    scanned upward, first P(maxDD>0.10) > 0.01 stops the scan. ONE index matrix per arm
    reused across all f (and for the half-Kelly DD probability). iid resampling ignores
    cycle-return autocorrelation / vol clustering — stated caveat.
  - Ruin print: measured P(r <= -100% of margin) per arm; at f=1 (full-margin
    compounding) one such cycle is ruin — the F17 headline restated as odds.
Run: PYTHONPATH=/home/user/claude-demo python3 scripts/opt_sweep/f18.py
"""
import math
import sys

import numpy as np
import pandas as pd

sys.path.insert(0, "/home/user/claude-demo")
sys.path.insert(0, "/home/user/claude-demo/scripts/opt_sweep")
import f16 as F16
import f17 as F17
from quant.ladder.credit_cycle import expanding_percentile

NSIMS = 20000
DD_BAR, DD_PROB = 0.10, 0.01
F_STEP_DD, F_STEP_K = 0.005, 0.001


def f16_margin_returns():
    """f16.run()'s hold/stop walk, verbatim, + per-unit-margin returns."""
    px = pd.read_csv(f"{F16.REPO}/ingest/vault/index/nifty50_daily_2007_2026.csv",
                     parse_dates=["Date"]).set_index("Date")["Adj Close"]
    vx = pd.read_csv(f"{F16.REPO}/ingest/vault/vix/india_vix_daily_2010_2023.csv",
                     parse_dates=["date"]).set_index("date")["close"]
    df = pd.concat({"S": px, "vix": vx}, axis=1, join="inner").dropna().sort_index()
    df["pct"] = expanding_percentile(df["vix"].values, min_obs=F16.MIN_OBS)
    S, V, P = df["S"].values, df["vix"].values / 100.0, df["pct"].values
    span_years = (df.index[-1] - df.index[F16.MIN_OBS - 1]).days / 365.25
    rh, rs = [], []
    for t0 in range(F16.MIN_OBS - 1, len(df) - F16.TENOR, F16.TENOR):
        if np.isnan(P[t0]) or P[t0] < F16.ENTRY_PCT:
            continue
        S0, sig0 = S[t0], V[t0]
        T0 = F16.TENOR / 252.0
        K0 = F16.make_strikes(S0, sig0, T0)
        C0, _, _ = F16.condor_mark(S0, K0, T0, sig0)
        margin = max(K0["kc2"] - K0["kc1"], K0["kp1"] - K0["kp2"]) - C0
        stop_pnl, stopped = None, False
        for j in range(1, F16.TENOR + 1):
            Trem = (F16.TENOR - j) / 252.0
            cost, _, _ = F16.condor_mark(S[t0 + j], K0, Trem, V[t0 + j])
            if not stopped and cost >= F16.STOP_MULT * C0:
                stop_pnl, stopped = C0 - cost, True
        hold_pnl = C0 - cost
        if not stopped:
            stop_pnl = hold_pnl
        rh.append(hold_pnl / margin)
        rs.append(stop_pnl / margin)
    return np.array(rh), np.array(rs), span_years


def f17_margin_returns():
    df = F17.load()
    valid = df[df["vixpct"].notna()]
    span_years = (valid.index[-1] - valid.index[0]).days / 365.25
    iso = valid.index.isocalendar()
    wk_groups = sorted([g.index for _, g in
                        valid.groupby([iso.year.values, iso.week.values])],
                       key=lambda d: d[0])
    wk = F17.sim_cycles(df, wk_groups)
    return (np.array([t["rh"] for t in wk]), np.array([t["rs"] for t in wk]),
            span_years)


def full_kelly(r):
    if r.mean() <= 0:
        return 0.0, np.nan
    fmax = 10.0 if r.min() >= 0 else 0.999 / abs(r.min())
    fs = np.arange(F_STEP_K, fmax, F_STEP_K)
    g = np.log1p(fs[:, None] * r[None, :]).mean(axis=1)
    i = int(g.argmax())
    return float(fs[i]), float(g[i])


def elog(r, f):
    return float(np.log1p(f * r).mean()) if f > 0 else 0.0


def growth_yr(r, f, rate):
    return 100.0 * (math.exp(rate * elog(r, f)) - 1.0)


def dd_prob(r, idx, f):
    W = np.cumprod(1.0 + f * r[idx], axis=1)
    peak = np.maximum(np.maximum.accumulate(W, axis=1), 1.0)
    return float(((1.0 - W / peak).max(axis=1) > DD_BAR).mean())


def dd_constrained(r, idx):
    fcap = 10.0 if r.min() >= 0 else 0.999 / abs(r.min())
    f_ok, f = 0.0, F_STEP_DD
    while f < fcap:
        if dd_prob(r, idx, f) <= DD_PROB:
            f_ok = f
            f += F_STEP_DD
        else:
            break
    return f_ok


def main():
    rh16, rs16, span16 = f16_margin_returns()
    rh17, rs17, span17 = f17_margin_returns()
    arms = [("F16-mo-hold", rh16, span16), ("F16-mo-stop2x", rs16, span16),
            ("F17-wk-hold", rh17, span17), ("F17-wk-stop", rs17, span17)]
    print(f"regenerated: F16 monthly n={len(rh16)} (span {span16:.2f}y), "
          f"F17 weekly n={len(rh17)} (span {span17:.2f}y); returns per unit margin")
    out = {}
    for name, r, span in arms:
        rate = len(r) / span
        n_cyc = max(1, round(rate))
        rng = np.random.default_rng(42)
        idx = rng.integers(0, len(r), size=(NSIMS, n_cyc))
        fstar, _ = full_kelly(r)
        fhalf = fstar / 2.0
        fdd = dd_constrained(r, idx)
        g_full = growth_yr(r, fstar, rate)
        g_half = growth_yr(r, fhalf, rate)
        g_dd = growth_yr(r, fdd, rate)
        p_half = dd_prob(r, idx, fhalf) if fhalf > 0 else 0.0
        p_full = dd_prob(r, idx, fstar) if fstar > 0 else 0.0
        ruin_odds = float((r <= -0.999).mean())
        out[name] = (fstar, g_full, p_full, fhalf, g_half, p_half, fdd, g_dd)
        print(f"\n[{name}] n={len(r)}, {rate:.2f} cycles/yr (bootstrap n_cyc={n_cyc}), "
              f"mean r {100*r.mean():+.2f}%/cycle, worst {100*r.min():+.1f}%, "
              f"P(r<=-100%) measured {100*ruin_odds:.1f}% of cycles")
        print(f"  full-Kelly  f*={fstar:.3f}: growth {g_full:+.1f}%/yr, "
              f"P(DD>10%/yr)={100*p_full:.1f}%")
        print(f"  half-Kelly  f ={fhalf:.3f}: growth {g_half:+.1f}%/yr, "
              f"P(DD>10%/yr)={100*p_half:.1f}%")
        print(f"  DD-constr   f ={fdd:.3f}: growth {g_dd:+.1f}%/yr "
              f"(largest f with P(maxDD>10%)<=1%/yr)")
    print("\nruin math at f=1 (full-margin compounding): F17 weekly hold has "
          f"{int((rh17 <= -0.999).sum())} measured -100% cycle(s) in {span17:.1f}y — "
          "P(ruin)=1 in-sample at f=1; Kelly caps the book far below full margin.")
    print("all three cells DESCRIPTIVE (analytic on measured odds; no PASS/MISS bar "
          "registered for F18).")


if __name__ == "__main__":
    main()
